version: "3.5"

services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/sonarr:/config
      - ${TV_DESTINATION_PATH}:/tv
      - ${PROCESSING_PATH}/downloads:/downloads
    ports:
      - "8989:8989"
    environment:
      PGID: $PGID
      PUID: $PUID
    restart: unless-stopped

  # Torrent Proxy
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/jackett:/config
      - ${PROCESSING_PATH}/jackett-downloads:/downloads
    ports:
      - "9117:9117"
    environment:
      PGID: $PGID
      PUID: $PUID
    restart: unless-stopped

#  Movies
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    volumes:
    - ${CONTAINERS_CONFIG_PATH}/radarr:/config
    - ${MOVIE_DESTINATION_PATH}:/movies
    - ${PROCESSING_PATH}/downloads:/downloads
    ports:
    - "7878:7878"
    environment:
      PGID: $PGID
      PUID: $PUID
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn:latest-armhf
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "51413:51413"
      - "51413:51413/udp"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${TV_DESTINATION_PATH}/downloads:/data/completed
      - ${PROCESSING_PATH}/downloads:/downloads
      - ${PROCESSING_PATH}/jackett-downloads:/data/watch
    environment:
      OPENVPN_PROVIDER: "PIA"
      OPENVPN_USERNAME: $PIA_USERNAME
      OPENVPN_PASSWORD: $PIA_PASSWORD
      TRANSMISSION_WATCH_DIR: /watch
      TRANSMISSION_WATCH_DIR_ENABLED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /downloads
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      PGID: $PGID
      PUID: $PUID

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - VERSION=docker
    volumes:
      - ${PLEX_CONFIG_PATH}:/config
      - ${TV_DESTINATION_PATH}:/tv
      - ${MOVIE_DESTINATION_PATH}:/movies
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
#      - "5353:5353/udp"
      - "1900:1900/udp"