version: "3.5"

services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/sonarr:/config
      - ${TV_DESTINATION_PATH}:/tv
      - ${PROCESSING_PATH}/completed:/data/completed
    ports:
      - "8989:8989"
    environment:
      PGID: $PGID
      PUID: $PUID
    restart: unless-stopped

  # Torrent Proxy
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/jackett:/config
      - ${PROCESSING_PATH}/jackett-downloads:/downloads
    ports:
      - "9117:9117"
    environment:
      PGID: $PGID
      PUID: $PUID
    restart: unless-stopped

#  Movies
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    volumes:
    - ${CONTAINERS_CONFIG_PATH}/radarr:/config
    - ${MOVIE_DESTINATION_PATH}:/movies
    - ${PROCESSING_PATH}/completed:/data/completed
    ports:
    - "7878:7878"
    environment:
      PGID: $PGID
      PUID: $PUID
    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn:latest-armhf
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "51413:51413"
      - "51413:51413/udp"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/transmission:/data/transmission-home
      - ${PROCESSING_PATH}/completed:/data/completed
      - ${PROCESSING_PATH}/incomplete:/data/incomplete
      - ${PROCESSING_PATH}/jackett-downloads:/data/watch
    environment:
      OPENVPN_PROVIDER: "PIA"
      OPENVPN_USERNAME: $PIA_USERNAME
      OPENVPN_PASSWORD: $PIA_PASSWORD
      TRANSMISSION_WATCH_DIR: /watch
      TRANSMISSION_WATCH_DIR_ENABLED: "true"
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      PGID: $PGID
      PUID: $PUID
      LOCAL_NETWORK: 192.168.1.0/24
      TRANSMISSION_WEB_UI: combustion

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/bazarr:/config
      - ${MOVIES_DESTINATION_PATH}:/movies
      - ${TV_DESTINATION_PATH}:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  plex:
    image: jaymoulin/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${PLEX_CONFIG_PATH}:/root/Library
      - ${TV_DESTINATION_PATH}:/media/tv
      - ${MOVIE_DESTINATION_PATH}:/media/movies
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
#      - "5353:5353/udp"
      - "1900:1900/udp"

  torproxy:
    container_name: torproxy
    image: schopenhauer/torpedo
    ports:
      - "8118:8118"
      - "9050:9050"
    restart: unless-stopped
