version: "3.5"

services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/sonarr:/config
      - ${TV_DESTINATION_PATH}:/tv
      - ${PROCESSING_PATH}/downloads:/downloads
    ports:
      - "8989:8989"
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped

  # Torrent Proxy
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/jackett:/config
      - ${PROCESSING_PATH}/jackett-downloads:/downloads
    ports:
      - "9117:9117"
    environment:
      PGID: 1000
      PUID: 1000
    restart: unless-stopped


  # Tor proxy so jackett can bypass ISP filters (NOT for anonymity - use something like Tails for that)
  torproxy:
    container_name: torproxy
    image: rdsubhas/tor-privoxy-alpine
    ports:
      - "8118:8118"
      - "9050:9050"
    restart: unless-stopped

  # Auto update containers
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    command: --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # Torrent Downloader
#  transmission:
#    container_name: transmission
#    image: linuxserver/transmission
#    volumes:
#      - ${CONTAINERS_CONFIG_PATH}/transmission:/config
#      - ${PROCESSING_PATH}/downloads:/downloads
#      - ${PROCESSING_PATH}/jackett-downloads:/watch
#    ports:
#      - "9091:9091"
#      - "51413:51413"
#      - "51413:51413/udp"
#    environment:
#      PGID: 1000
#      PUID: 1000
#    restart: unless-stopped

  transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "51413:51413"
      - "51413:51413/udp"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ${PROCESSING_PATH}/downloads:/downloads
      - ${PROCESSING_PATH}/jackett-downloads:/watch
    environment:
      OPENVPN_PROVIDER: "PIA"
      OPENVPN_USERNAME: $PIA_USERNAME
      OPENVPN_PASSWORD: $PIA_PASSWORD
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
      PGID: $PGID
      PUID: $PUID

  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - VERSION=docker
    volumes:
      - ${CONTAINERS_CONFIG_PATH}/plex:/config
      - ${TV_DESTINATION_PATH}:/tv
      - ${MOVIE_DESTINATION_PATH}:/movies
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
#      - "5353:5353/udp"
      - "1900:1900/udp"