#!/bin/bash

cd ~

echo "Updating and Upgrading"
sudo apt-get update && sudo apt-get upgrade -y

echo "Ensure required tools installed"
sudo apt-get install apt-transport-https  ca-certificates curl  gnupg-agent software-properties-common git vim jq rpcbind nfs-kernel-server samba exfat-fuse exfat-utils minidlna -y

if [[ -z $(docker --version | grep 'Docker version') ]]; then
  echo "Install Docker"
  curl -sSL https://get.docker.com | sh

  sudo apt-get install -y libffi-dev libssl-dev  python3 python3-pip

  sudo pip3 install docker-compose

  sudo groupadd docker
  sudo usermod -aG docker $USER

  sudo systemctl enable docker
fi

if [[ -z $(ls | grep 'home-server') ]]; then
  echo "Clone Repos"
  git clone https://github.com/wayrunner/home-server.git
else
  echo "Update Repos"
  cd ~/home-server
  git pull
  cd ~
fi

# update sshd_config
#if [[ -z $(sudo cat /etc/ssh/sshd_config | grep 'damon') ]]; then
#  echo "Update sshd_config"
#  sudo cp -p /etc/ssh/sshd_config /etc/ssh/sshd_config.old
#  sudo sed -ri 's/^#?Port .*/Port 57400/' /etc/ssh/sshd_config
#  sudo sed -ri 's/^#?PermitRootLogin .*/PermitRootLogin no/' /etc/ssh/sshd_config
#  sudo sed -ri 's/^#?PubkeyAuthentication .*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
#  sudo sed -ri 's/^#?PasswordAuthentication .*/PasswordAuthentication no/' /etc/ssh/sshd_config
#  sudo sed -i "\$aAllowUsers damon" /etc/ssh/sshd_config
#  sudo sed -i "\$aProtocol 2" /etc/ssh/sshd_config
#  sudo service ssh restart
#fi

# setup fstab
if [[ -z $(sudo cat /etc/fstab | grep 'alpha') ]]; then
  echo "Update fstab"
  sudo mkdir /media/wdred-alpha
  sudo mkdir /media/wdred-bravo

  sudo sed -i "\$aUUID=b0dc81d1-becf-4f75-aece-3cbadc499b91 /media/wdred-alpha ext4 defaults 0 0" /etc/fstab
  sudo sed -i "\$aUUID=4A5E-2179 /media/wdred-bravo exfat user,owner,utf8,rw,umask=000 0 0" /etc/fstab
fi

# setup nfs
echo "Setup nfs"
if [[ -z $(sudo cat /etc/exports | grep 'alpha') ]]; then
  echo "Update exports"
  sudo touch /etc/exports
  sudo sed -i "\$a/media/wdred-alpha 192.168.1.0/255.255.255.0(rw,async,insecure,no_subtree_check,all_squash,anonuid=1000,anongid=1000)" /etc/exports
  sudo sed -i "\$a/media/wdred-bravo 192.168.1.0/255.255.255.0(rw,async,insecure,no_subtree_check,all_squash,anonuid=1000,anongid=1000)" /etc/exports
  sudo systemctl start nfs-kernel-server.service
fi

# setup samba
echo "Setup samba"
if [[ -z $(sudo cat /etc/samba/smb.conf | grep 'alpha') ]]; then
  echo "Update smb.conf"
  sudo -- bash -c 'echo  "   guest account = pi" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "[raspberry]" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "  comment = Raspberry" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "  path = /media/wdred-alpha" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "  read only = no" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "  browsable = yes" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "  guest only = yes" >> /etc/samba/smb.conf'
  sudo -- bash -c 'echo  "  guest ok = yes" >> /etc/samba/smb.conf'
  sudo service smbd restart
fi

# setup wireguard
echo "Setup wireguard"

echo "cleanup"
sudo apt-get autoremove
